"""empty message

Revision ID: 3c5f39001c65
Revises: 
Create Date: 2019-03-07 10:23:20.437236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5f39001c65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lyric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rili',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=8), nullable=True),
    sa.Column('jsonContent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rili')
    op.drop_table('lyric')
    # ### end Alembic commands ###
