"""empty message

Revision ID: 4cb1e05fe980
Revises: 9e7fdfe63ab5
Create Date: 2019-03-07 11:49:13.421667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb1e05fe980'
down_revision = '9e7fdfe63ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lyric', sa.Column('album', sa.String(length=50), nullable=True))
    op.add_column('lyric', sa.Column('song', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lyric', 'song')
    op.drop_column('lyric', 'album')
    # ### end Alembic commands ###
