"""empty message

Revision ID: 9b117a5dfc1d
Revises: 
Create Date: 2019-03-17 21:45:31.152451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b117a5dfc1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lyric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=50), nullable=True),
    sa.Column('song', sa.String(length=50), nullable=True),
    sa.Column('album', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rili',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=8), nullable=True),
    sa.Column('jsonContent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('rili')
    op.drop_table('lyric')
    op.drop_table('contact')
    # ### end Alembic commands ###
