"""empty message

Revision ID: 9e7fdfe63ab5
Revises: 3c5f39001c65
Create Date: 2019-03-07 11:47:42.754794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7fdfe63ab5'
down_revision = '3c5f39001c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lyric', sa.Column('artist', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lyric', 'artist')
    # ### end Alembic commands ###
