"""add class <Contact>

Revision ID: f567fd1cf1d0
Revises: 3d35bc01e75f
Create Date: 2019-03-13 13:54:24.002272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f567fd1cf1d0'
down_revision = '3d35bc01e75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_city'), 'contact', ['city'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_city'), table_name='contact')
    op.drop_table('contact')
    # ### end Alembic commands ###
